name: cuvs-mgpu-benchmark
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - python=3.12
  - cuvs=26.04
  - rmm=26.04
  - cuda-python=12.9
  - matplotlib
  - numpy=2.4
  - pyarrow=24
  - black
  - ruff
  - pip
  - pip:
      - nvtx==0.2.15
