TRAIN_PATHS = [
    "../openai_large_5m/train-00-of-10.parquet",
    "../openai_large_5m/train-01-of-10.parquet",
    "../openai_large_5m/train-02-of-10.parquet",
    "../openai_large_5m/train-03-of-10.parquet",
]
TRAIN_PATH = TRAIN_PATHS[0]
QUERY_PATH = "../openai_large_5m/test.parquet"
VECTOR_DIM = 1536
ID_COLUMN = "id"
EMBEDDING_COLUMN = "emb"

N_LISTS = 1024
N_PROBES_SWEEP = [8, 16, 32, 64, 128]
K = 10
METRIC = "sqeuclidean"
DISTRIBUTION_MODE = "sharded"
SEARCH_MODE = "load_balancer"
MERGE_MODE = "merge_on_root_rank"

GROUND_TRUTH_TOP_K = 100
QUERY_LIMIT = 1000
GROUND_TRUTH_BATCH_SIZE = 10
BENCHMARK_QUERY_COUNT = 1000
DISPLAY_TOP_K = 10
MS_PER_SECOND = 1000.0
SEARCH_WARMUP_RUNS = 3
SEARCH_TIMED_RUNS = 10
ONLINE_QUERY_COUNT = 1
OFFLINE_QUERY_COUNT = BENCHMARK_QUERY_COUNT

CAGRA_DIM = 96
CAGRA_GRAPH_DEGREE = 32
CAGRA_INTERMEDIATE_GRAPH_DEGREE = 64
CAGRA_NUM_VECTORS = 1000000
CAGRA_NUM_QUERIES = 10000
CAGRA_NEW_VECTORS = 100000
CAGRA_HNSW_M = 16

IVFPQ_EXAMPLE_NUM_SAMPLES = 100000
IVFPQ_EXAMPLE_DIM = 96
IVFPQ_EXAMPLE_NUM_QUERIES = 10000
IVFPQ_EXAMPLE_N_PROBES = 20
