import os
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = Path(os.environ.get("CUVS_BENCH_DATA_DIR", PROJECT_ROOT / "openai_large_5m")).expanduser()
RESULTS_DIR = PROJECT_ROOT / "results"

TRAIN_PATHS = [
    DATA_DIR / "train-00-of-10.parquet",
    DATA_DIR / "train-01-of-10.parquet",
    DATA_DIR / "train-02-of-10.parquet",
    DATA_DIR / "train-03-of-10.parquet",
    DATA_DIR / "train-04-of-10.parquet",
    DATA_DIR / "train-05-of-10.parquet",
    DATA_DIR / "train-06-of-10.parquet",
    DATA_DIR / "train-07-of-10.parquet",
    DATA_DIR / "train-08-of-10.parquet",
    DATA_DIR / "train-09-of-10.parquet",
]
TRAIN_PATH = TRAIN_PATHS[0]
QUERY_PATH = DATA_DIR / "test.parquet"
VECTOR_DIM = 1536
ID_COLUMN = "id"
EMBEDDING_COLUMN = "emb"
DATA_CACHE_DIR = Path(os.environ.get("CUVS_BENCH_DATA_CACHE_DIR", PROJECT_ROOT / "data_cache")).expanduser()
USE_DATA_CACHE = os.environ.get("CUVS_BENCH_USE_DATA_CACHE", "1") != "0"
DATA_CACHE_MMAP = os.environ.get("CUVS_BENCH_DATA_CACHE_MMAP", "1") != "0"

N_LISTS_SWEEP = [512, 1024, 2048, 4096]
N_LISTS = N_LISTS_SWEEP[1]
N_PROBES_SWEEP = [8, 16, 32, 64, 128]
K = 10
METRIC = "sqeuclidean"
DISTRIBUTION_MODE = "sharded"
SEARCH_MODE = "load_balancer"
MERGE_MODE = "merge_on_root_rank"

GROUND_TRUTH_TOP_K = 100
QUERY_LIMIT = 1000
GROUND_TRUTH_BATCH_SIZE = 10
GROUND_TRUTH_CACHE_DIR = Path(
    os.environ.get("CUVS_BENCH_GROUND_TRUTH_CACHE_DIR", PROJECT_ROOT / "ground_truth_cache")
).expanduser()
BENCHMARK_QUERY_COUNT = 1000
DISPLAY_TOP_K = 10
MS_PER_SECOND = 1000.0
SEARCH_WARMUP_RUNS = 3
SEARCH_TIMED_RUNS = 10
ONLINE_QUERY_COUNT = 1
OFFLINE_QUERY_COUNT = BENCHMARK_QUERY_COUNT

CAGRA_DIM = 96
CAGRA_GRAPH_DEGREE = 32
CAGRA_INTERMEDIATE_GRAPH_DEGREE = 64
CAGRA_NUM_VECTORS = 1000000
CAGRA_NUM_QUERIES = 10000
CAGRA_NEW_VECTORS = 100000
CAGRA_HNSW_M = 16

IVFPQ_EXAMPLE_NUM_SAMPLES = 100000
IVFPQ_EXAMPLE_DIM = 96
IVFPQ_EXAMPLE_NUM_QUERIES = 10000
IVFPQ_EXAMPLE_N_PROBES = 20


# IVF-PQ sweep configuration.
IVFPQ_N_LISTS_SWEEP = [1024, 2048, 4096]
IVFPQ_N_PROBES_SWEEP = [32, 64, 128]

IVFPQ_PQ_BITS_SWEEP = [4, 6, 8]
IVFPQ_PQ_DIM_SWEEP = [384, 768, 1536]

IVFPQ_KMEANS_N_ITERS = 20
IVFPQ_KMEANS_TRAINSET_FRACTION = 0.5
IVFPQ_CODEBOOK_KIND = "subspace"
IVFPQ_FORCE_RANDOM_ROTATION = False
IVFPQ_CONSERVATIVE_MEMORY_ALLOCATION = True
IVFPQ_MAX_TRAIN_POINTS_PER_PQ_CODE = 256
IVFPQ_CODES_LAYOUT = "interleaved"
IVFPQ_RERANK_CANDIDATE_K = 100
IVFPQ_ENABLE_EXACT_RERANK = True
IVFPQ_RERANK_BATCH_SIZE = int(os.environ.get("CUVS_BENCH_IVFPQ_RERANK_BATCH_SIZE", "512"))
IVFPQ_RERANK_BACKEND = os.environ.get("CUVS_BENCH_IVFPQ_RERANK_BACKEND", "multi_gpu")
IVFPQ_RERANK_DEVICE_ID = int(os.environ.get("CUVS_BENCH_IVFPQ_RERANK_DEVICE_ID", "0"))
_IVFPQ_RERANK_DEVICE_IDS_RAW = os.environ.get("CUVS_BENCH_IVFPQ_RERANK_DEVICE_IDS", "")
IVFPQ_RERANK_DEVICE_IDS = (
    [int(device_id.strip()) for device_id in _IVFPQ_RERANK_DEVICE_IDS_RAW.split(",") if device_id.strip()]
    if _IVFPQ_RERANK_DEVICE_IDS_RAW.strip()
    else None
)

# IVF-PQ input/search precision. Lower precision can improve speed/memory use,
# but it can also move nearest-neighbor rankings and change recall.
IVFPQ_DATASET_DTYPE = "float16"
IVFPQ_QUERY_DTYPE = "float16"
IVFPQ_LUT_DTYPE = "float16"
IVFPQ_INTERNAL_DISTANCE_DTYPE = "float16"
IVFPQ_COARSE_SEARCH_DTYPE = "float16"
IVFPQ_MAX_INTERNAL_BATCH_SIZE = 4096
